# Generated by Django 4.2.20 on 2025-04-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bom_no', models.CharField(max_length=15, unique=True)),
                ('depth', models.IntegerField()),
                ('complexity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('P', 'Part'), ('A', 'Assembly')], max_length=1)),
                ('base_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wc_no', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('cost_per_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_no', models.CharField(max_length=20)),
                ('step_no', models.IntegerField()),
                ('run_time_min', models.IntegerField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing', to='bom_app.bom')),
                ('wc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom_app.workcenter')),
            ],
        ),
        migrations.CreateModel(
            name='BOMLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='bom_app.bom')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bom_app.item')),
            ],
        ),
        migrations.AddField(
            model_name='bom',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booms', to='bom_app.item'),
        ),
    ]
