# Generated by Django 4.2.20 on 2025-04-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='process_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
